name: Build & Push Multi-Arch Docker Images

on:
  push:
    # branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  SERVICES: go-admin gate-keeper gatari-db-init
  DOCKER_NAMESPACE: bignya

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”„ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ“¦ Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: ðŸ” Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ðŸ—ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ§± Build and Push Multi-Arch Docker Images
        run: |
          GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
          GIT_HASH=$(git rev-parse --short HEAD)

          for SERVICE in $SERVICES; do
            IMAGE_NAME=${DOCKER_NAMESPACE}/${SERVICE}
            TAG=${GIT_TAG:-$GIT_HASH}

            echo "ðŸš€ Building and pushing $IMAGE_NAME:$TAG..."

            make build-container \
              SERVICE_NAME=$SERVICE \
              PLATFORM=linux/amd64,linux/arm64 \
              CONTAINER_IMAGE_TAG=$TAG \
              DOCKER_NAMESPACE=$DOCKER_NAMESPACE

            docker push $IMAGE_NAME:$TAG

            if [ -n "$GIT_TAG" ]; then
              docker push $IMAGE_NAME:$GIT_TAG
            fi

            docker push $IMAGE_NAME:latest
          done